### ISSUE TITLE
华为Mate30 Pro 鸿蒙OS 4.2 添加盒子IP连接后，点击连接后闪退。1.0-1.02版本都挨个试，均闪退

### ISSUE THREAD

**Issue by hnsycxm** [SX-Code/ADBRemoteATV#1]
-      你好，谢谢开源了这么好的手机遥控APP，一直想找一款手机可以控制盒子还能输入文字的APP,
- 找了2-3款年限久远，UI简陋的APP，使用起来都不尽如意，直到发现了这款开源APP，非常的高兴，
- 这是我看到的目前功能最为多，UI最为好看的。可安装后，并不能正常使用，希望能得到解决。
- 
-     使用环境：华为Mate30 Pro 鸿蒙OS 4.2 添加盒子IP连接后，点击连接状况如下
- 
- 1、添加盒子IP后，默认5555端口，与盒子在同一网络下，点击连接，就闪退。
-      多次尝试都如此，1.0-1.02版本都试过了，都是如此。断开或不和盒子在同一网络下，点击连接，一直转圈，提示连接失 
       败， 不闪退。  
- 
-     希望能够得到解决。谢谢了
- 
-

**Comment by SX-Code** [comment]
抱歉，我手头没有搭载鸿蒙的设备，无法定位问题

**Comment by sxczst** [comment]
我在使用中也发现了同样的问题
程序报错如下：

 E  FATAL EXCEPTION: Thread-3
                                                                                                    Process: com.swx.adbremote, PID: 5110
                                                                                                    java.lang.Error: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
                                                                                                    	at javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:907)
                                                                                                    	at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155)
                                                                                                    	at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:626)
                                                                                                    	at com.swx.adbremote.utils.ADBConnectUtil.$r8$lambda$SoMTrePo-sjmEGeChmWvStCD860(Unknown Source:0)
                                                                                                    	at com.swx.adbremote.utils.ADBConnectUtil$$ExternalSyntheticLambda2.encodeToString(Unknown Source:0)
                                                                                                    	at com.swx.adbremote.adblib.AdbCrypto.getAdbPublicKeyPayload(AdbCrypto.java:225)
                                                                                                    	at com.swx.adbremote.adblib.AdbConnection$1.run(AdbConnection.java:188)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
                                                                                                    	at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:106)
                                                                                                    	at javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:905)
                                                                                                    	at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155) 
                                                                                                    	at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:626) 
                                                                                                    	at com.swx.adbremote.utils.ADBConnectUtil.$r8$lambda$SoMTrePo-sjmEGeChmWvStCD860(Unknown Source:0) 
                                                                                                    	at com.swx.adbremote.utils.ADBConnectUtil$$ExternalSyntheticLambda2.encodeToString(Unknown Source:0) 
                                                                                                    	at com.swx.adbremote.adblib.AdbCrypto.getAdbPublicKeyPayload(AdbCrypto.java:225) 
                                                                                                    	at com.swx.adbremote.adblib.AdbConnection$1.run(AdbConnection.java:188) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl" on path: DexPathList[[zip file "/data/app/com.swx.adbremote-7x15UPst3zXUJUD1sSXksQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.swx.adbremote-7x15UPst3zXUJUD1sSXksQ==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at javax.xml.datatype.FactoryFinder.newInstance(FactoryFinder.java:157)
                                                                                                    	at javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:223)
                                                                                                    	at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:99)
                                                                                                    	at javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:905) 
                                                                                                    	at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155) 
                                                                                                    	at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:626) 
                                                                                                    	at com.swx.adbremote.utils.ADBConnectUtil.$r8$lambda$SoMTrePo-sjmEGeChmWvStCD860(Unknown Source:0) 
                                                                                                    	at com.swx.adbremote.utils.ADBConnectUtil$$ExternalSyntheticLambda2.encodeToString(Unknown Source:0) 
                                                                                                    	at com.swx.adbremote.adblib.AdbCrypto.getAdbPublicKeyPayload(AdbCrypto.java:225) 
                                                                                                    	at com.swx.adbremote.adblib.AdbConnection$1.run(AdbConnection.java:188) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
 
在网上搜索后 得知需要添加如下依赖
implementation 'xerces:xercesImpl:2.12.0'
重新编译即可正常使用。

**Comment by hnsycxm** [comment]
不会编译，请问有编译好的，能发我吗？393032651@qq.com   谢谢

**Comment by hnsycxm** [comment]
> 我在使用中也发现了同样的问题 程序报错如下：
> 
> E FATAL EXCEPTION: Thread-3 Process: com.swx.adbremote, PID: 5110 java.lang.Error: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found at javax.xml.bind.DatatypeConverterImpl.(DatatypeConverterImpl.java:907) at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155) at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:626) at com.swx.adbremote.utils.ADBConnectUtil.$r8$lambda$SoMTrePo-sjmEGeChmWvStCD860(Unknown Source:0) at com.swx.adbremote.utils.ADBConnectUtil$$ExternalSyntheticLambda2.encodeToString(Unknown Source:0) at com.swx.adbremote.adblib.AdbCrypto.getAdbPublicKeyPayload(AdbCrypto.java:225) at com.swx.adbremote.adblib.AdbConnection$1.run(AdbConnection.java:188) at java.lang.Thread.run(Thread.java:764) Caused by: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:106) at javax.xml.bind.DatatypeConverterImpl.(DatatypeConverterImpl.java:905) at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155)  at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:626)  at com.swx.adbremote.utils.ADBConnectUtil.$r8$lambda$SoMTrePo-sjmEGeChmWvStCD860(Unknown Source:0)  at com.swx.adbremote.utils.ADBConnectUtil$$ExternalSyntheticLambda2.encodeToString(Unknown Source:0)  at com.swx.adbremote.adblib.AdbCrypto.getAdbPublicKeyPayload(AdbCrypto.java:225)  at com.swx.adbremote.adblib.AdbConnection$1.run(AdbConnection.java:188)  at java.lang.Thread.run(Thread.java:764)  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl" on path: DexPathList[[zip file "/data/app/com.swx.adbremote-7x15UPst3zXUJUD1sSXksQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.swx.adbremote-7x15UPst3zXUJUD1sSXksQ==/lib/arm64, /system/lib64, /vendor/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at javax.xml.datatype.FactoryFinder.newInstance(FactoryFinder.java:157) at javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:223) at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:99) at javax.xml.bind.DatatypeConverterImpl.(DatatypeConverterImpl.java:905)  at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155)  at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:626)  at com.swx.adbremote.utils.ADBConnectUtil.$r8$lambda$SoMTrePo-sjmEGeChmWvStCD860(Unknown Source:0)  at com.swx.adbremote.utils.ADBConnectUtil$$ExternalSyntheticLambda2.encodeToString(Unknown Source:0)  at com.swx.adbremote.adblib.AdbCrypto.getAdbPublicKeyPayload(AdbCrypto.java:225)  at com.swx.adbremote.adblib.AdbConnection$1.run(AdbConnection.java:188)  at java.lang.Thread.run(Thread.java:764) 
> 
> 在网上搜索后 得知需要添加如下依赖 implementation 'xerces:xercesImpl:2.12.0' 重新编译即可正常使用。

编译好的app能发我吗，393032651@qq.com，谢谢

**Comment by SX-Code** [comment]
以增加该依赖，并发布APK1.0.3
